# .github/workflows/commit-badge.yml
name: Update commit badge
on:
  push:
  schedule:
    - cron:  '0 * * * *'   # hourly
jobs:
  build-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          count=$(git rev-list --count HEAD)
          npx badge --label "COMMITS" --message "$count" \
                    --color blue --labelColor 1e2024 > badges/commits.svg
      - run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/commits.svg
          git commit -m "chore: update commit badge" || echo "No changes"
          git push
