
name: Aggregate commit badge
on:
  schedule:      [ { cron: '17 * * * *' } ]
  workflow_dispatch:

permissions: { contents: write }

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4   # provides `npx`

      - name: Sum commits across repos
        env: { GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} }
        run: |
          repos="Promptee another-repo third-repo"
          owner="attilagrynaeus"
          total=0
          for repo in $repos; do
            c=$(gh api graphql -f query='
              { repository(owner:"'$owner'",name:"'$repo'"){
                  defaultBranchRef{ target{ ... on Commit{ history{ totalCount }}}}}}'
              --jq '.data.repository.defaultBranchRef.target.history.totalCount')
            total=$(( total + c ))
          done
          echo "TOTAL=$total" >> $GITHUB_ENV

      - name: Create SVG badge
        run: |
          npx --yes badge --label COMMITS --message "$TOTAL" \
               --color blue --labelColor 1e2024 > badges/commits.svg

      - name: Commit and push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/commits.svg
          git diff --cached --quiet || { git commit -m "chore: badge ($TOTAL)" && git push ;}
