name: Supabase keep-alive task

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ping Supabase
        id: call
        run: |
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' \
            -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            "$SUPABASE_URL/rest/v1/?select=1")
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Append result to log
        run: |
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          STATUS="${{ steps.call.outputs.status }}"
          echo "$TS  Supabase keep-alive  HTTP:$STATUS" >> .supabase-ping.log

      - name: Commit and push log
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .supabase-ping.log
          git commit -m "chore: log Supabase ping (HTTP:${{ steps.call.outputs.status }})" || echo "Nothing to commit"
          git push

      - name: Fail workflow on bad status
        if: steps.call.outputs.status != '200'
        run: |
          echo "::error::Unexpected HTTP ${{ steps.call.outputs.status }}"
          exit 1
