# .github/workflows/commit-badge.yml
name: Update commit badge

on:
  push:                       # every push to main
    branches: [ main ]
  schedule:                   # once per hour
    - cron: '17 * * * *'      # hh:17 UTC
  workflow_dispatch:          # manual trigger button

permissions:
  contents: write             # required for git commit & push

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      # 1 ▸ check out repo
      - uses: actions/checkout@v4

      - name: Generate commit badge
        uses: FMorschel/commit-count-badge@v1
        with:
          repository: ${{ github.repository }}   # current repo
          text: COMMITS                          # label on the badge
          outputPath: badges/commits.svg         # where to save SVG
          token: ${{ secrets.GITHUB_TOKEN }}     # auto-injected

      - name: Commit and push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add badges/commits.svg
          git diff --cached --quiet && echo "No changes" || \
            (git commit -m "chore: update commit badge" && git push)
