name: Supabase keep-alive

on:
  schedule:
    - cron: '0 3 * * *'           # every day @ 03:00 UTC
  workflow_dispatch:              # manual trigger button

env:
  SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ check out repo so we can append the log file
      - uses: actions/checkout@v4

      # 2 ▸ ping Supabase REST endpoint
      - name: Ping Supabase
        id: call
        run: |
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' \
            -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            "$SUPABASE_URL/rest/v1/?select=1")
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      # 3 ▸ append result to plaintext log inside repo
      - name: Append result to log
        run: |
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          STATUS="${{ steps.call.outputs.status }}"
          echo "$TS  Supabase keep-alive  HTTP:$STATUS" >> .supabase-ping.log

      # 4 ▸ commit & push the log on every run
      - name: Commit and push log
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .supabase-ping.log
          git commit -m "chore: log Supabase ping (HTTP:${{ steps.call.outputs.status }})" \
            || echo "Nothing to commit"
          git push

      # 5 ▸ fail workflow (so GitHub sends e-mail) if status ≠ 200
      - name: Fail workflow on bad status
        if: steps.call.outputs.status != '200'
        run: |
          echo "::error::Unexpected HTTP ${{ steps.call.outputs.status }}"
          exit 1
